### ISSUE TITLE
Links gone bad

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritSpellCheck#10]
http://drdhaval2785.github.io/o_vs_O/output1/MW.html

@funderburkjim
Earlier the links used to work on the following address
http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=MW&key=apatyasac
Now all the dictionaries refer to the first page of the word.

Can you please check and let me which link should work for getting a PDF based on dictionary name and the input word ?

This issue is raised by @gasyoun in a skype chat. 
Placing it here for future tracking.

**Comment by gasyoun** [comment]
@funderburkjim had raised the issue few weeks ago, here we go again. Now I have copypaste every word, so I do believe it's fixable, thanks.

**Comment by funderburkjim** [comment]
The link above now works, so I think the bug is now eradicated.

The bug came into existence when the [sample displays](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/) were extended to work for all the dictionaries.

**Comment by drdhaval2785** [comment]
Tested.
Works fine.
@gasyoun's issue now stands resolved with the existing data itself. 
Closing the issue
